// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { SubjectType } from "./SubjectType";

export type AccessRow = { entity_type: SubjectType, entity_id: number, 
/**
 * Carried so the receiving side can show who this is without an ESI lookup.
 */
entity_name: string | null, 
/**
 * `viewer` / `member` / `manager`; the owner row never leaves a map.
 */
permission: Role, expires_at: string | null, };
