// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubjectType } from "./SubjectType";

/**
 * A grantable subject from the access-subject search.
 */
export type AccessSubject = { subject_type: SubjectType, subject_id: number, name: string, ticker: string | null, };
