// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { WormholeSize } from "./WormholeSize";

export type AddConnection = { map_id: number, from_system: number, to_system: number, kind: ConnectionType, 
/**
 * Initial max ship size, when the client can infer it (e.g. a C13 endpoint is
 * frigate-sized). `None` = unknown.
 */
size?: WormholeSize, };
