// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JumpDirection } from "./JumpDirection";

export type AddConnectionJump = { map_id: number, connection_id: number, direction: JumpDirection, ship_type_id?: number, 
/**
 * Explicit mass in kg; wins over the ship type's hull mass.
 */
mass?: number, };
