// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the client sends to put a hub's holes on the map: the list itself is the server's,
 * fetched fresh so a stale card cannot map holes that have since collapsed.
 */
export type AddEveScoutToMap = { map_id: number, hub_solar_system_id: number, 
/**
 * Where to put the hub if it is not on the map yet; the server picks otherwise.
 */
x?: number, y?: number, };
