// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WormholeSize } from "./WormholeSize";

export type AddGhostSystem = { map_id: number, 
/**
 * The placement the signature was scanned in. The ghost hangs off it.
 */
from_system: number, 
/**
 * The wormhole signature this hole is, so the two stay in lock-step from the start.
 */
signature_pk?: number, x: number, y: number, alias?: string, size?: WormholeSize, };
