// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { SignatureGroup } from "./SignatureGroup";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

export type AddSignature = { map_id: number, solar_system_id: number, signature_id: string, group: SignatureGroup, name?: string, size?: WormholeSize, mass_status?: MassStatus, time_status?: TimeStatus, };
