// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddSystem = { map_id: number, solar_system_id: number, x: number, y: number, alias: string | null, };
