// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the message goes.
 */
export type AlertDelivery = "webhook" | "discord_dm" | "discord_channel";
