// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who gets pinged when an alert fires.
 */
export type AlertMention = "none" | "creator" | "role" | "everyone";
