// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an alert watches for.
 */
export type AlertKind = "killmail" | "proximity" | "jump_range";
