// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a chain names itself: the sequence an alias suggestion walks.
 */
export type AliasScheme = "numeric" | "alphabetical";
