// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the image sits under the map. `Grid` spans the whole world and moves with the
 * systems; `Viewport` fills the visible panel and stays put.
 */
export type BackgroundMode = "grid" | "viewport";
