// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutItem } from "./LayoutItem";

/**
 * One breakpoint's arrangement.
 */
export type BreakpointLayout = { cols: number, row_height: number, items: Array<LayoutItem>, };
