// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live status of the active character, for the navbar readout.
 */
export type CharacterStatus = { online: boolean, solar_system: string | null, ship_type_id: number | null, ship_name: string | null, ship_type: string | null, };
