// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the user's characters, for the switcher.
 */
export type CharacterRef = { character_id: number, name: string, is_active: boolean, online: boolean, };
