// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The signed-in character, for the UI's auth state.
 */
export type CharacterSummary = { character_id: number, name: string, };
