// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { WireLifetime } from "./WireLifetime";
import type { WireMassStatus } from "./WireMassStatus";
import type { WireShipSize } from "./WireShipSize";

export type ConnectionRow = { from_solarsystem_id: number, to_solarsystem_id: number, 
/**
 * The wormhole code name ("K162"), when one is known.
 */
wormhole: string | null, type: ConnectionType, mass_status: WireMassStatus, ship_size: WireShipSize, lifetime: WireLifetime, lifetime_updated_at: string | null, connected_at: string | null, preserve_mass: boolean, };
