// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of edge between two placed systems.
 */
export type ConnectionType = "wormhole" | "stargate";
