// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonalAccessToken } from "./PersonalAccessToken";

/**
 * The one response that carries the secret.
 */
export type CreatedToken = { token: PersonalAccessToken, plaintext: string, };
