// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateMap = { name: string, description: string | null, 
/**
 * How the chain is placed: `manual` or `tree`. Absent starts on `manual`, which is
 * what a map dragged into shape by hand needs.
 */
layout?: string, };
