// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an alert stopped firing, so the settings page can say more than "off".
 */
export type DisabledReason = "manual" | "discord_unlinked" | "access_revoked" | "destination_gone" | "delivery_failed";
