// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A linked account, as the frontend shows it.
 */
export type DiscordAccount = { discord_user_id: string, username: string, display_name?: string, avatar?: string, };
