// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordCapability = { 
/**
 * Whether an account can be linked at all: the OAuth half of the application.
 */
linking: boolean, 
/**
 * Whether the bot can post to a channel or DM. Needs a bot token on top of the rest;
 * a plain webhook destination works without it.
 */
bot: boolean, };
