// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One buff/debuff a wormhole effect applies, for the node's effect popover. `kind` is the
 * effect strength tier; `stat` is what it modifies; `value` is the (already-formatted) amount.
 */
export type EffectModifier = { kind: string, stat: string, value: string, };
