// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A public wormhole out of Thera or Turnur, as EVE Scout's scouts have it. Oriented
 * hub-first rather than in EVE Scout's in/out terms, and statuses normalized to WormholeSystems's
 * own vocabulary.
 */
export type EveScoutConnection = { hub_solar_system_id: number, 
/**
 * `Thera` or `Turnur`.
 */
hub: string, hub_signature: string, solar_system_id: number, signature: string, mass_status: string, time_status: string, 
/**
 * The wormhole code, e.g. `J377`. Absent while a scout has only half-scanned it.
 */
wormhole_type?: string, 
/**
 * `frigate` / `medium` / `large` / `capital`.
 */
max_ship_size?: string, remaining_hours?: number, 
/**
 * When a scout last touched it, for the card's freshness stamp.
 */
updated_at?: string, };
