// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A public Thera/Turnur wormhole edge from EVE Scout, normalized to Vector's status
 * vocabulary for the client-side router.
 */
export type EveScoutEdge = { from_solar_system_id: number, to_solar_system_id: number, mass_status: string, time_status: string, };
