// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sections } from "./Sections";

export type ExportFile = { format: string, version: number, exported_at: string, map_name: string, sections: Sections, };
