// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GotoMapEvent = { map_id: number, 
/**
 * The step to move the map onto. `null` rewinds to before the first step, which is a
 * real destination rather than an omitted field, so it is nullable and not optional.
 */
event_id: number | null, };
