// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Map canvas geometry. Server-owned (built from env in `crate::config`), fetched by the
 * client so layout has a single source of truth. Node height is `2 * cell_size`;
 * dimensions are world-space px.
 */
export type GridConfig = { cell_size: number, world_width: number, world_height: number, viewport_height: number, };
