// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionCounts } from "./SectionCounts";

export type ImportSummary = { settings: SectionCounts, access: SectionCounts, systems: SectionCounts, connections: SectionCounts, signatures: SectionCounts, routes: SectionCounts, };
