// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordCapability } from "./DiscordCapability";

/**
 * What this deployment can actually do, so the interface can say what is switched off
 * rather than offering something that will quietly never arrive. Self-hosters configure
 * Discord separately from the rest, and most of them do not configure it at all.
 */
export type Instance = { discord: DiscordCapability, };
