// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way a manual jump went, relative to the connection's `from_system` endpoint.
 */
export type JumpDirection = "outbound" | "inbound";
