// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JumpShip = "dreadnought" | "carrier" | "force_auxiliary" | "supercarrier" | "titan" | "jump_freighter" | "rorqual" | "black_ops";
