// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of the chain the killmails card shows.
 */
export type KillmailScope = "all" | "jspace" | "kspace";
