// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tile. Minimum sizes are deliberately absent: they belong to the panel, not to
 * anyone's arrangement, so they live in the client's panel registry where tightening one
 * still reaches people who have already saved a layout.
 */
export type LayoutItem = { 
/**
 * Panel id. Named `i` to match the stored shape.
 */
i: string, x: number, y: number, w: number, h: number, };
