// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkSignature = { map_id: number, signature_pk: number, connection_id: number, };
