// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapNaming } from "./MapNaming";

export type Map = { id: number, name: string, description: string | null, image_url: string | null, created_at: string, naming: MapNaming, 
/**
 * Whether pasting a wormhole signature puts its far side on the map as a ghost.
 * Map-wide: a ghost is a node everyone on the chain sees.
 */
ghost_unlinked_wormholes: boolean, };
