// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapLayout } from "./MapLayout";
import type { MapNaming } from "./MapNaming";

export type Map = { id: number, name: string, description: string | null, image_url: string | null, created_at: string, naming: MapNaming, 
/**
 * Whether pasting a wormhole signature puts its far side on the map as a ghost.
 * Map-wide: a ghost is a node everyone on the chain sees.
 */
ghost_unlinked_wormholes: boolean, 
/**
 * How the chain is placed: `manual` (dragged into shape) or `tree` (drawn from the
 * connections). Map-wide, so everyone on a chain reads the same picture.
 */
layout: MapLayout, 
/**
 * Whether a viewer may pick their own placement instead of the map's.
 */
allow_layout_override: boolean, 
/**
 * Whether anyone with the address may watch it, account or no account.
 */
is_public: boolean, 
/**
 * The secret that lets somebody watch a private map. Only ever sent to a manager:
 * handing it to a viewer would be handing them the map to pass on.
 */
share_token?: string, };
