// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of an alert's history.
 */
export type MapAlertEvent = { id: number, map_alert_id?: number, alert_name?: string, actor?: string, kind: string, detail?: string, created_at: string, };
