// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An online, tracked character on the map (presence), for the node pilot rows.
 */
export type MapCharacter = { character_id: number, name: string, corporation_ticker: string, solar_system_id: number | null, ship_type_id: number | null, ship_name: string | null, ship_type: string | null, };
