// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

export type MapConnection = { id: number, map_id: number, from_system: number, to_system: number, kind: ConnectionType, 
/**
 * Wormhole life-cycle state. `None` = unknown; ignored for stargate edges. Synced with
 * linked signatures by the DB triggers, so reads here already reflect the merged state.
 */
mass_status: MassStatus | null, time_status: TimeStatus | null, size: WormholeSize | null, 
/**
 * Exclude this hole from mass bookkeeping (legacy flag; stored, not yet consumed).
 */
preserve_mass: boolean, 
/**
 * When `time_status` last changed (DB trigger), for "EOL since" displays.
 */
time_status_updated_at: string | null, 
/**
 * How long a hole between these two systems lives, from the class pair (see the
 * [life-cycle spec](../../docs/processes.md#connection-life-cycle)). `None` for
 * stargates. With `created_at`, the client's countdown.
 */
lifetime_hours: number | null, 
/**
 * Full jump-log aggregates (the log itself is fetched separately, capped at 10).
 */
jumps_count: number, jumps_mass_sum: number, created_at: string, updated_at: string, };
