// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An online, tracked character on the map (presence), for the node pilot rows and the
 * pilots card.
 */
export type MapCharacter = { character_id: number, name: string, corporation_ticker: string, solar_system_id: number | null, ship_type_id: number | null, 
/**
 * The name the pilot gave the hull, which is not the hull's type.
 */
ship_name: string | null, ship_type: string | null, 
/**
 * The hull's inventory group, so the client can tell a covert-ops scanner from a
 * combat ship without shipping a table of hull names.
 */
ship_group_id: number | null, 
/**
 * Docked in a station or structure: on the map, but not on grid.
 */
is_docked: boolean, 
/**
 * One of the viewer's own characters, so their alts can be told apart at a glance.
 */
is_mine: boolean, };
