// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

export type MapConnection = { id: number, map_id: number, from_system: number, to_system: number, kind: ConnectionType, 
/**
 * Wormhole life-cycle state. `None` = unknown; ignored for stargate edges. Synced with
 * linked signatures by the DB triggers, so reads here already reflect the merged state.
 */
mass_status: MassStatus | null, time_status: TimeStatus | null, size: WormholeSize | null, 
/**
 * Exclude this hole from mass bookkeeping (legacy flag; stored, not yet consumed).
 */
preserve_mass: boolean, 
/**
 * When `time_status` last changed (DB trigger), for "EOL since" displays.
 */
time_status_updated_at: string | null, created_at: string, updated_at: string, };
