// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map in the user's list, with their role on it.
 */
export type MapEntry = { id: number, name: string, description?: string, role: string, system_count: number, connection_count: number, 
/**
 * How many people can see it, counting every grant however it was made.
 */
member_count: number, 
/**
 * Tracked pilots currently online in one of its systems.
 */
pilots_online: number, 
/**
 * Whether this user keeps it in the top bar.
 */
is_pinned: boolean, 
/**
 * When the chain last changed. `None` for a map nobody has touched yet.
 */
last_activity?: string, 
/**
 * Hidden from this user's list. Per-user, so archiving does not touch anyone else.
 */
is_archived: boolean, created_at: string, };
