// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapEventEntry = { id: number, map_id: number, character_id: number | null, 
/**
 * Actor name, or `None` for background tasks.
 */
character_name: string | null, kind: string, label: string, entries_count: number, 
/**
 * Whether this entry carries an inverse and has not been undone yet.
 */
undoable: boolean, undone_at: string | null, 
/**
 * The entry this one reverted, if any (undo/redo chains).
 */
reverts_id: number | null, created_at: string, };
