// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapEventEntry = { id: number, map_id: number, character_id: number | null, 
/**
 * Actor name, or `None` for background tasks.
 */
character_name: string | null, kind: string, label: string, entries_count: number, 
/**
 * The step this one was applied on top of. `None` for a root, or for an audit row.
 */
parent_id: number | null, 
/**
 * Whether this row is a step in the tree. Audit-only rows (background writers) are
 * shown in the history but cannot be jumped to.
 */
is_step: boolean, 
/**
 * Whether this step is currently in effect, i.e. on the path from a root to the head.
 */
applied: boolean, created_at: string, };
