// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map in the user's list, with their role on it.
 */
export type MapEntry = { id: number, name: string, role: string, };
