// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change to a map that its viewers should react to. Carries ids, not data — consumers
 * refetch the named slice.
 */
export type MapEvent = { "type": "map_updated", map_id: number, } | { "type": "system_added", map_id: number, map_solar_system_id: number, } | { "type": "system_moved", map_id: number, map_solar_system_id: number, } | { "type": "system_removed", map_id: number, map_solar_system_id: number, } | { "type": "system_details_changed", map_id: number, map_solar_system_id: number, } | { "type": "connection_changed", map_id: number, connection_id: number, } | { "type": "signature_changed", map_id: number, solar_system_id: number, } | { "type": "access_changed", map_id: number, };
