// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapEventEntry } from "./MapEventEntry";

/**
 * The history as the status bar needs it: the entries plus where the map is sitting.
 */
export type MapHistory = { entries: Array<MapEventEntry>, 
/**
 * The step the map is on. `None` means every step has been undone.
 */
head_event_id: number | null, 
/**
 * The step undo would move to (`None` when already at a root and nothing is applied).
 */
undo_target: number | null, 
/**
 * The step redo would move to.
 */
redo_target: number | null, can_undo: boolean, can_redo: boolean, };
