// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KillParty } from "./KillParty";

/**
 * A killmail as the card shows it: what a row renders, not the raw payload.
 */
export type MapKillmail = { id: number, solar_system_id: number, system_name: string, region: string, security_status: number, wormhole_class_id?: number, time: string, victim: KillParty, final_blow: KillParty, total_value?: number, attacker_count: number, is_npc: boolean, is_solo: boolean, };
