// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the nodes get their positions. `Manual` keeps whatever they were dragged to;
 * `Tree` derives them, and is the map's choice unless it hands it to each viewer.
 */
export type MapLayout = "manual" | "tree";
