// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a map names its chain. Map-wide rather than per-user, because an alias is written
 * on the map for everyone and a bookmark folder in three conventions is unreadable.
 */
export type MapNaming = { 
/**
 * `numeric` (`1`, `11`, `12`) or `alphabetical` (`A`, `AB`, with `H/L/N/P` reserved
 * for k-space exits).
 */
alias_scheme: string, 
/**
 * The alias that sits outside the chain, e.g. `HOME`.
 */
ignored_alias: string, bookmark_wormhole: string, bookmark_kspace: string, bookmark_return: string, };
