// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sovereignty } from "./Sovereignty";
import type { Static } from "./Static";
import type { SystemStatus } from "./SystemStatus";
import type { ThreatLevel } from "./ThreatLevel";

/**
 * A placed system enriched with everything a map node displays. Read-only — built by
 * `get_map` from joins across the SDE + intel + sovereignty tables. Mutations use the lean
 * [`MapSolarSystem`].
 */
export type MapSystemView = { id: number, map_id: number, solar_system_id: number, position_x: number, position_y: number, alias: string | null, is_home: boolean, is_rally: boolean, is_pinned: boolean, status: SystemStatus, occupying_group: string | null, name: string, security_status: number, wormhole_class_id: number | null, region: string, region_id: number, constellation_id: number, constellation: string, effect_name: string | null, is_shattered: boolean, 
/**
 * Kill-activity threat (wormhole systems only; `None` for k-space).
 */
threat_level: ThreatLevel | null, statics: Array<Static>, sovereignty: Sovereignty | null, };
