// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapSolarSystem = { id: number, map_id: number, solar_system_id: number, position_x: number, position_y: number, alias: string | null, created_at: string, };
