// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hit from the map command palette. `map_solar_system_id` is set when the system is
 * already placed; otherwise the hit is an off-map system the palette can add.
 */
export type MapSearchHit = { solar_system_id: number, map_solar_system_id: number | null, name: string, region: string, security: number, wormhole_class_id: number | null, alias: string | null, occupying_group: string | null, 
/**
 * The matching slice of the system's notes, when the query hit the notes. Member+ only.
 */
note_excerpt: string | null, 
/**
 * Why this row matched: `name`, `alias`, `occupier`, or `notes`.
 */
matched: string, };
