// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemSearchResult } from "./SystemSearchResult";
import type { ThreatMatch } from "./ThreatMatch";

/**
 * One hit from the map command palette. `map_solar_system_id` is set when the system is
 * already placed; otherwise the hit is an off-map system the palette can add.
 */
export type MapSearchHit = { system: SystemSearchResult, map_solar_system_id: number | null, alias: string | null, occupying_group: string | null, 
/**
 * The matching slice of the system's notes, when the query hit the notes. Member+ only.
 */
note_excerpt: string | null, 
/**
 * The organisation that made this system a hit, when the query named a threat group.
 */
threat?: ThreatMatch, 
/**
 * Why this row matched: `name`, `alias`, `occupier`, `notes`, or `threat`.
 */
matched: string, };
