// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakpointLayout } from "./BreakpointLayout";

/**
 * A user's per-map preferences.
 */
export type MapUserSettings = { tracking_allowed: boolean, show_threat_level: boolean, compact_signature_list: boolean, show_statics_first: boolean, 
/**
 * `shorter` / `safer` / `less_secure`.
 */
route_preference: string, 
/**
 * 0-100, weight of the security preference (legacy `exp(0.15 * penalty)`).
 */
security_penalty: number, 
/**
 * Worst wormhole lifetime still routed through: `stable` / `eol` / `critical`.
 */
route_allow_time_status: string, 
/**
 * Worst wormhole mass still routed through: `stable` / `reduced` / `critical`.
 */
route_allow_mass_status: string, route_use_evescout: boolean, 
/**
 * Ask which signature was jumped, rather than mapping the hole unlinked.
 */
prompt_for_signature: boolean, 
/**
 * Prefill the jump dialog's alias from the chain's naming scheme.
 */
suggest_alias: boolean, 
/**
 * Put the new connection's bookmark on the clipboard once the jump is mapped.
 */
copy_bookmark: boolean, 
/**
 * Panels this user hides on this map. Empty = the built-in set. A hidden panel keeps
 * its saved position, so unhiding puts it back where it was.
 */
hidden_panels: Array<string>, 
/**
 * Per-breakpoint tile positions. `None` = the built-in arrangement.
 */
layout_breakpoints?: { [key in string]: BreakpointLayout }, };
