// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BreakpointLayout } from "./BreakpointLayout";
import type { KillmailScope } from "./KillmailScope";
import type { MapLayout } from "./MapLayout";
import type { MassStatus } from "./MassStatus";
import type { RoutePreference } from "./RoutePreference";
import type { TimeStatus } from "./TimeStatus";

/**
 * A user's per-map preferences.
 */
export type MapUserSettings = { tracking_allowed: boolean, show_threat_level: boolean, compact_signature_list: boolean, show_statics_first: boolean, route_preference: RoutePreference, 
/**
 * 0-100, weight of the security preference (legacy `exp(0.15 * penalty)`).
 */
security_penalty: number, 
/**
 * Worst wormhole lifetime still routed through.
 */
route_allow_time_status: TimeStatus, 
/**
 * Worst wormhole mass still routed through.
 */
route_allow_mass_status: MassStatus, route_use_evescout: boolean, 
/**
 * Ask which signature was jumped, rather than mapping the hole unlinked.
 */
prompt_for_signature: boolean, 
/**
 * Prefill the jump dialog's alias from the chain's naming scheme.
 */
suggest_alias: boolean, 
/**
 * Put the new connection's bookmark on the clipboard once the jump is mapped.
 */
copy_bookmark: boolean, 
/**
 * Which half of the chain the killmails card shows.
 */
killmail_filter: KillmailScope, is_archived: boolean, 
/**
 * Whether this user has been through the map's introduction.
 */
introduction_confirmed: boolean, 
/**
 * Panels this user hides on this map. Empty = the built-in set. A hidden panel keeps
 * its saved position, so unhiding puts it back where it was.
 */
hidden_panels: Array<string>, 
/**
 * This viewer's placement choice, when the map hands it to them. `None` follows the
 * map's own mode.
 */
layout_override?: MapLayout, 
/**
 * Whether this user keeps the map in the top bar for quick access.
 */
is_pinned: boolean, 
/**
 * Per-breakpoint tile positions. `None` = the built-in arrangement.
 */
layout_breakpoints?: { [key in string]: BreakpointLayout }, };
