// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Map } from "./Map";
import type { MapConnection } from "./MapConnection";
import type { MapSystemView } from "./MapSystemView";

/**
 * The graph as seen by a viewer: the map plus its placed systems and connections.
 */
export type MapView = { map: Map, systems: Array<MapSystemView>, connections: Array<MapConnection>, };
