// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered role, so alerts ping "Scouts" rather than 1189734502938472.
 */
export type MapWebhookRole = { id: number, name: string, discord_role_id: string, };
