// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registered destination, named once and pointed at by any number of alerts.
 */
export type MapWebhook = { id: number, name: string, 
/**
 * Enough of the URL to tell two destinations apart, never enough to use one: the URL is
 * a bearer token for somebody's channel, and every manager reads this list.
 */
summary: string, 
/**
 * How many alerts would stop working if this were deleted.
 */
alert_count: number, };
