// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wormhole's remaining mass, worst last. Variant order is the severity order the
 * [reconcile-on-link merge](../../docs/database/mapping.md) relies on: `max` is the
 * worst (= "massed"). Kept in lock-step across a connection and its signatures by the
 * `map_*_sync` DB triggers (migration 0009).
 */
export type MassStatus = "stable" | "reduced" | "critical";
