// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemMove } from "./SystemMove";

export type MoveSystems = { map_id: number, moves: Array<SystemMove>, };
