// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureGroup } from "./SignatureGroup";

/**
 * One row of a parsed scanner paste. `group` is `None` when the scanner line carried no
 * classification (legacy: keep whatever the row already has). The catalog type is only
 * ever client-matched for site categories; wormhole types never come from a paste.
 */
export type PastedSignature = { signature_id: string, group?: SignatureGroup, signature_type_id?: number, name?: string, };
