// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PastedSignature } from "./PastedSignature";

export type PasteSignatures = { map_id: number, solar_system_id: number, signatures: Array<PastedSignature>, };
