// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureGroup } from "./SignatureGroup";

export type PastedSignature = { signature_id: string, group: SignatureGroup, name: string | null, };
