// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A token as the account settings list it: everything except the secret.
 */
export type PersonalAccessToken = { id: number, name: string, last_used_at?: string, expires_at?: string, created_at: string, };
