// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which reagent a skyhook's planet yields, which is the only reason anyone sorts them.
 * Derived from the planet's type name rather than a list of type ids, so a new variant
 * (the shattered ones, say) classifies itself.
 */
export type PlanetKind = "lava" | "ice" | "other";
