// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of New Eden this install has loaded. The landing page states these, so they
 * are the real contents of this database rather than numbers written into a page.
 */
export type ReferenceCounts = { solar_systems: number, wormhole_systems: number, stargates: number, wormhole_types: number, };
