// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Say which system a ghost turned out to be. `solar_system_id: None` takes it back to a
 * ghost, and exists as the inverse of the first form rather than as an action of its own.
 */
export type ResolveGhostSystem = { map_id: number, map_solar_system_id: number, solar_system_id?: number, };
