// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

/**
 * Say which system a ghost turned out to be. `solar_system_id: None` takes it back to a
 * ghost, and exists as the inverse of the first form rather than as an action of its own.
 *
 * The rest is what flying the hole taught us about it, carried here rather than sent as
 * follow-up writes so that one jump stays one undo. All of it is ignored when taking a
 * node back to a ghost.
 */
export type ResolveGhostSystem = { map_id: number, map_solar_system_id: number, solar_system_id?: number, alias?: string, size?: WormholeSize, mass_status?: MassStatus, time_status?: TimeStatus, };
