// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map access role, ordered `Viewer < Member < Manager < Owner`.
 */
export type Role = "viewer" | "member" | "manager" | "owner";
