// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a route is optimised for.
 */
export type RoutePreference = "shorter" | "safer" | "less_secure";
