// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationGroup } from "./StationGroup";

/**
 * The static half of the routing graph, typed and built once: k-space stargate
 * adjacency (Zarzakh excluded since its gates are faction-gated), per-system security
 * for the safer/less-secure cost functions, and the station indexes the planner offers.
 */
export type RoutingGraph = { adjacency: { [key in number]: Array<number> }, security: { [key in number]: number }, jove: Array<number>, stations: Array<number>, services: Array<StationGroup>, corporations: Array<StationGroup>, };
