// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IgnoredRow } from "./IgnoredRow";
import type { RouteRow } from "./RouteRow";

export type RoutesSection = { route_solarsystems: Array<RouteRow>, 
/**
 * The map's ignore list: routed around by everyone, never placed by jump tracking.
 */
ignored_solarsystems: Array<IgnoredRow>, };
