// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IgnoredRow } from "./IgnoredRow";
import type { RouteRow } from "./RouteRow";

export type RoutesSection = { route_solarsystems: Array<RouteRow>, 
/**
 * Router-avoided systems, a legacy feature vector does not have: exported empty,
 * skipped on import.
 */
ignored_solarsystems: Array<IgnoredRow>, };
