// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";
import type { Side } from "./Side";
import type { Subject } from "./Subject";

/**
 * One rule. The ids within a rule are an OR: "any of these alliances".
 */
export type Rule = { subject: Subject, side: Side, mode: Mode, ids: Array<number>, };
