// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveWebhook = { name: string, 
/**
 * Write-only. Absent on an update keeps the stored one.
 */
url?: string, };
