// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertDelivery } from "./AlertDelivery";
import type { AlertKind } from "./AlertKind";
import type { AlertMention } from "./AlertMention";
import type { JumpShip } from "./JumpShip";
import type { Match } from "./Match";
import type { Rule } from "./Rule";

export type SaveAlert = { name: string, kind: AlertKind, delivery: AlertDelivery, 
/**
 * Which registered destination to post to.
 */
map_webhook_id?: number, discord_guild_id?: string, discord_channel_id?: string, 
/**
 * Which registered role to ping.
 */
map_webhook_role_id?: number, mention: AlertMention, target_solar_system_id?: number, 
/**
 * Proximity only: measure from here through the chain instead of from the nearest
 * mapped system.
 */
origin_solar_system_id?: number, max_jumps: number, ship_type?: JumpShip, jdc_level?: number, filters: Array<Rule>, filter_match: Match, };
