// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertDelivery } from "./AlertDelivery";
import type { AlertKind } from "./AlertKind";
import type { AlertMention } from "./AlertMention";
import type { Match } from "./Match";
import type { Rule } from "./Rule";

export type SaveAlert = { name: string, kind: AlertKind, delivery: AlertDelivery, 
/**
 * Write-only. Absent on an update leaves the stored one alone.
 */
webhook_url?: string, discord_guild_id?: string, discord_channel_id?: string, discord_role_id?: string, mention: AlertMention, target_solar_system_id?: number, max_jumps: number, filters: Array<Rule>, filter_match: Match, };
