// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ESI permission and whether the acting character has consented to it.
 */
export type ScopeStatus = { scope: string, granted: boolean, };
