// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one section of an import.
 */
export type SectionCounts = { created: number, updated: number, skipped: number, };
