// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessRow } from "./AccessRow";
import type { ConnectionRow } from "./ConnectionRow";
import type { RoutesSection } from "./RoutesSection";
import type { SettingsSection } from "./SettingsSection";
import type { SignatureRow } from "./SignatureRow";
import type { SolarsystemRow } from "./SolarsystemRow";

/**
 * Only the sections that were asked for are present; on import, only the requested ones
 * are read at all, so a broken section nobody selected does not fail the file.
 */
export type Sections = { settings?: SettingsSection, access?: Array<AccessRow>, solarsystems?: Array<SolarsystemRow>, connections?: Array<ConnectionRow>, signatures?: Array<SignatureRow>, routes?: RoutesSection, };
