// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the server is doing, as one word for the client to render.
 */
export type ServerState = "unknown" | "online" | "vip" | "offline" | "unreachable";
