// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerState } from "./ServerState";

export type ServerStatus = { state: ServerState, players: number, server_version?: string, 
/**
 * When this run of the server started, for the uptime readout.
 */
start_time?: string, 
/**
 * When we last asked. A stale value here means *our* poller is stuck, not the server.
 */
checked_at?: string, };
