// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { SubjectType } from "./SubjectType";

export type SetAccess = { map_id: number, subject_type: SubjectType, subject_id: number, role: Role, };
