// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionType } from "./ConnectionType";
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

/**
 * A partial update of a connection's wormhole state. `None` leaves a field unchanged;
 * `Some(None)` clears it to unknown; `Some(Some(v))` sets it. Setting any field triggers
 * the DB sync, so linked signatures follow.
 */
export type SetConnectionStatus = { map_id: number, connection_id: number, 
/**
 * `None` leaves the edge kind unchanged; `Some(k)` switches wormhole/stargate.
 */
kind?: ConnectionType, mass_status?: MassStatus | null, time_status?: TimeStatus | null, size?: WormholeSize | null, };
