// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetOccupier = { map_id: number, map_solar_system_id: number, occupier: string | null, };
