// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemStatus } from "./SystemStatus";

export type SetStatus = { map_id: number, map_solar_system_id: number, status: SystemStatus, };
