// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasScheme } from "./AliasScheme";
import type { MapLayout } from "./MapLayout";

export type SettingsSection = { name: string, layout: MapLayout, allow_layout_override: boolean, 
/**
 * A legacy display setting vector does not have; exported as `false`, ignored on
 * import, kept so the file validates over there.
 */
constant_width_enabled: boolean, bookmark_format_wormhole: string, bookmark_format_kspace: string, bookmark_format_return: string, bookmark_alias_scheme: AliasScheme, bookmark_ignored_alias: string | null, home_solarsystem_id: number | null, rally_solarsystem_id: number | null, };
