// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetWaypointAllBody = { destination_id: number, add_to_beginning?: boolean, clear_other_waypoints?: boolean, };
