// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A ship type matched by the manual-jump ship search.
 */
export type ShipSearchResult = { id: number, name: string, group_name: string, 
/**
 * Hull mass in kg.
 */
mass: number | null, };
