// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which end of the killmail to look at.
 */
export type Side = "victim" | "attacker" | "either";
