// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cosmic-signature category from the seeded catalog.
 */
export type SignatureCategoryInfo = { id: number, name: string, code: string, };
