// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cosmic-signature type from the seeded catalog. `signature` is the wormhole code
 * (wormhole types only); `target_class` its destination class; `spawn_areas` the system
 * classes this type can appear in.
 */
export type SignatureTypeInfo = { id: number, signature: string | null, name: string, signature_category_id: number, target_class: number | null, extra: string | null, spawn_areas: Array<number>, };
