// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureCategoryInfo } from "./SignatureCategoryInfo";
import type { SignatureTypeInfo } from "./SignatureTypeInfo";

/**
 * The full signature catalog, served once and cached client-side.
 */
export type SignatureCatalog = { categories: Array<SignatureCategoryInfo>, types: Array<SignatureTypeInfo>, };
