// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A cosmic-signature group, mirroring [`signature_categories`](../../docs/database/static.md).
 * Only `Wormhole` signatures carry connection links and the wormhole life-cycle state.
 */
export type SignatureGroup = "wormhole" | "data" | "relic" | "gas" | "combat" | "ore" | "homefront" | "unknown";
