// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WireLifetime } from "./WireLifetime";
import type { WireMassStatus } from "./WireMassStatus";
import type { WireShipSize } from "./WireShipSize";

export type SignatureRow = { solarsystem_id: number, 
/**
 * The in-game scanner id ("ABC-123"). Legacy allows signatures without one; vector
 * does not, so those are skipped on import.
 */
signature_id: string | null, 
/**
 * The category code ("wormhole", "data", ...). Unmatched codes import as `unknown`.
 */
category: string | null, 
/**
 * The catalog type by name; both applications seed the catalog from the same data,
 * so names resolve on either side.
 */
type_name: string | null, raw_type_name: string | null, wormhole: string | null, 
/**
 * Index into this file's `connections` array, when the signature is one end of one.
 */
connection_index: number | null, mass_status: WireMassStatus | null, ship_size: WireShipSize | null, lifetime: WireLifetime | null, lifetime_updated_at: string | null, };
