// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { SignatureGroup } from "./SignatureGroup";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

export type Signature = { id: number, map_id: number, solar_system_id: number, 
/**
 * The in-game scanner id, e.g. `ABC-123`. Unique per `(map, system)`.
 */
signature_id: string, group: SignatureGroup, name: string | null, size: WormholeSize | null, mass_status: MassStatus | null, time_status: TimeStatus | null, 
/**
 * The connection this signature is one end of, if linked. Only `wormhole` sigs.
 */
connection_id: number | null, created_at: string, updated_at: string, };
