// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanetKind } from "./PlanetKind";

/**
 * A raidable skyhook, enriched with everything a row displays.
 */
export type Skyhook = { planet_id: number, 
/**
 * e.g. `4-EP12 VI`, as it reads in the overview.
 */
planet_name: string, planet_kind: PlanetKind, solar_system_id: number, system_name: string, region: string, security_status: number, vulnerable_from: string, vulnerable_until: string, };
