// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemStatus } from "./SystemStatus";

export type SolarsystemRow = { solarsystem_id: number, alias: string | null, 
/**
 * Null positions mean intel without a placement: the system is not on the canvas,
 * but its status and notes are kept.
 */
position_x: number | null, position_y: number | null, pinned: boolean | null, status: SystemStatus, occupier_alias: string | null, notes: string | null, };
