// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who holds sovereignty in a system. The variant *is* the holder kind, so the node knows
 * which EVE image endpoint to use for the icon; only alliances/corps carry a ticker.
 */
export type Sovereignty = { "kind": "alliance", id: number, name: string, ticker: string, } | { "kind": "corporation", id: number, name: string, ticker: string, } | { "kind": "faction", id: number, name: string, };
