// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stale edge, for the status bar's cleanup popover.
 */
export type StaleConnection = { connection_id: number, from_name: string, to_name: string, critical_since: string, };
