// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A static wormhole a system always has, plus the class it leads to (`dest_class` is the
 * `wormhole_class_id` encoding; `None` for the few codes with no fixed destination) and
 * the hole physics for the static tooltip.
 */
export type Static = { code: string, dest_class: number | null, 
/**
 * Total mass the hole can pass before collapsing, kg.
 */
total_mass: number | null, 
/**
 * Max mass of a single ship per jump, kg.
 */
max_jump_mass: number | null, lifetime_hours: number | null, 
/**
 * Scan signature strength in percent (higher = easier to scan).
 */
signature_strength: number | null, };
