// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StationRef } from "./StationRef";

/**
 * A named set of stations: a service, or the corporation that owns them.
 */
export type StationGroup = { id: number, name: string, stations: Array<StationRef>, };
