// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a rule is about.
 */
export type Subject = "ship_type" | "ship_group" | "character" | "corporation" | "alliance";
