// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an access grant targets. EVE ids are globally unique across the three.
 */
export type SubjectType = "character" | "corporation" | "alliance";
