// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A solar system matched by the "add system" search, with just enough to display and pick.
 */
export type SystemSearchResult = { id: number, name: string, security: number, region: string, wormhole_class_id: number | null, };
