// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A placed system's intel status (`map_solar_system_details.status`), set by users.
 * Matches the legacy vocabulary: `active` = recent activity seen, `empty` = scanned
 * and found empty.
 */
export type SystemStatus = "unknown" | "friendly" | "hostile" | "active" | "unscanned" | "empty";
