// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A placed system's member-gated intel details (currently just the notes). Viewers never
 * receive this: the read itself requires Member.
 */
export type SystemDetails = { notes: string | null, };
