// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sovereignty } from "./Sovereignty";
import type { Static } from "./Static";

/**
 * A solar system matched by the "add system" search, with just enough to display and pick.
 */
export type SystemSearchResult = { id: number, name: string, security: number, region: string, region_id: number, constellation_id: number, wormhole_class_id: number | null, 
/**
 * Wormhole effect, for J-space rows (shown where k-space rows show sovereignty).
 */
effect_name: string | null, sovereignty: Sovereignty | null, 
/**
 * The statics a wormhole always has. Empty for k-space.
 */
statics: Array<Static>, };
