// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wormhole system's kill-activity threat level, from the daily analysis.
 */
export type ThreatLevel = "unknown" | "high" | "critical";
