// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreatEntity } from "./ThreatEntity";
import type { ThreatLevel } from "./ThreatLevel";

/**
 * A wormhole system's threat analysis, for the threat card.
 */
export type ThreatAnalysis = { threat_level: ThreatLevel, threat_analyzed_at: string | null, entities: Array<ThreatEntity>, };
