// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One organisation in a system's threat top list.
 */
export type ThreatEntity = { id: number, name: string, entity_type: string, kills: number, };
