// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An organisation the threat analysis found operating in a system, as the palette shows it.
 */
export type ThreatMatch = { entity_id: number, 
/**
 * `alliance` or `corporation`.
 */
entity_type: string, name: string, 
/**
 * Kills this organisation has in this system over the analysis window.
 */
kills: number, };
