// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wormhole's remaining lifetime, worst last. `Eol` ≈ "<4h"; `Critical` ≈ "<1h"
 * (super-EOL). Same severity-ordering / merge semantics as [`MassStatus`].
 */
export type TimeStatus = "stable" | "eol" | "critical";
