// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

export type TrackJump = { map_id: number, 
/**
 * The placement the character jumped *from*; it anchors the new system.
 */
from_map_solar_system_id: number, to_solar_system_id: number, 
/**
 * Where to put the new system. The client owns the layout, so it picks the spot.
 */
x: number, y: number, 
/**
 * The signature that turned out to be this hole. `None` = jumped an unscanned one.
 */
signature_pk?: number, alias?: string, size?: WormholeSize, mass_status?: MassStatus, time_status?: TimeStatus, };
