// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TransferOwnership = { map_id: number, 
/**
 * The character taking it on. They keep no second role: there is one owner.
 */
subject_id: number, };
