// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of the map each section would carry, for the export UI. Manager+.
 */
export type TransferCounts = { access: number, systems: number, connections: number, signatures: number, routes: number, };
