// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

/**
 * A partial edit of a signature's resolved name and wormhole state. `None` leaves a field
 * unchanged; `Some(None)` clears it. The group is fixed at add time (remove + re-add to
 * change it). Editing a linked wormhole's state propagates to its connection via the DB
 * trigger.
 */
export type UpdateSignature = { map_id: number, signature_pk: number, name?: string | null, size?: WormholeSize | null, mass_status?: MassStatus | null, time_status?: TimeStatus | null, };
