// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JumpDirection } from "./JumpDirection";

export type UpdateConnectionJump = { map_id: number, jump_pk: number, direction?: JumpDirection, ship_type_id?: number | null, 
/**
 * Explicit mass in kg. Absent while the ship type changes → mass re-derives.
 */
mass?: number, };
