// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapNaming } from "./MapNaming";

/**
 * A partial update of a map's fields. `None` leaves a field unchanged; `Some(None)`
 * explicitly clears a nullable field.
 */
export type UpdateMap = { map_id: number, name?: string, description?: string | null, image_url?: string | null, 
/**
 * All-or-nothing: the naming block is edited as one form, so a partial payload here
 * would only ever mean a half-saved form.
 */
naming?: MapNaming, ghost_unlinked_wormholes?: boolean, layout?: string, allow_layout_override?: boolean, is_public?: boolean, };
