// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update of [`MapUserSettings`]; absent fields stay unchanged.
 */
export type UpdateMapUserSettings = { tracking_allowed?: boolean, show_threat_level?: boolean, };
