// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MassStatus } from "./MassStatus";
import type { SignatureGroup } from "./SignatureGroup";
import type { TimeStatus } from "./TimeStatus";
import type { WormholeSize } from "./WormholeSize";

/**
 * A partial edit of a signature. `None` leaves a field unchanged; `Some(None)` clears it.
 * Changing the group clears the catalog type, the connection link, and any wormhole state
 * (matching the legacy category select), unless a new type is supplied in the same call.
 * Editing a linked wormhole's state propagates to its connection via the DB trigger.
 */
export type UpdateSignature = { map_id: number, signature_pk: number, 
/**
 * `Some` renames the scanner id (7 chars; duplicate in the system → `Conflict`).
 */
signature_id?: string, group?: SignatureGroup, signature_type_id?: number | null, name?: string | null, size?: WormholeSize | null, mass_status?: MassStatus | null, time_status?: TimeStatus | null, };
