// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial update of a map's fields. `None` leaves a field unchanged; `Some(None)`
 * explicitly clears a nullable field.
 */
export type UpdateMap = { map_id: number, name?: string, description?: string | null, image_url?: string | null, };
