// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An event addressed to a single user.
 */
export type UserEvent = { "type": "character_status_changed", character_id: number, };
