// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy's lifetime vocabulary has no "unknown": `healthy` is both vector's `stable` and
 * its null, and imports as the null (nothing remarkable to show).
 */
export type WireLifetime = "healthy" | "eol" | "critical";
