// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy's mass vocabulary. Vector's `stable` is legacy's `fresh`, and vector says
 * "unknown" with a null.
 */
export type WireMassStatus = "fresh" | "reduced" | "critical" | "unknown";
