// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy names hole sizes by the ship class that fits through.
 */
export type WireShipSize = "frigate" | "medium" | "large" | "xlarge";
